sudo: true
dist: xenial
language: python
python:
- '2.7'
- '3.6'
- '3.7'
git:
  depth: false
env:
- MPLBACKEND=Agg
cache: pip
install:
- if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh
  -O miniconda.sh; else wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
  -O miniconda.sh; fi
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
- conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION chainer pytorch
  -c pytorch
- source activate test-environment
- pip install torchvision
- pip install moviepy==0.2.3.2
- pip install matplotlib
- python -c "import imageio; imageio.plugins.ffmpeg.download()"
- pip install --upgrade pytest flake8
- pip install .
script:
- python example_fc.py
deploy:
  provider: pypi
  user: jshenk
  skip_cleanup: true
  on:
    tags: true
    branch: master
  password:
    secure: Rq2n7BemMkHbgm6H5GqMrUjnaNcukTBeQU3BpbZW4nVlIsuH+bmHgJ2pJpj7bKrBnWfF94d58f7lrdTSSv0qNdiNsUgZszS+osZ/ai1tdL5NuXa2u/abeUV+9bmDtZpnWQxAKZFlwC8EhTxIJ8Mxygmf8rV+cj4hgtWkFS5CRbjaid5sjUuneog8ozOa7DpPVs1P7QBjqppSfMj9Ke4mkpZeQCC6rn/X5GJUZUEAJOfEZ4x1grRZ2wBDVnk4zUd6Kb1EqElJaXg+gjkpIrPBOkJfxu2/opmb6MUvknxWWvNzRL90Sx2i9aB/jMI5XU5sd0GiCUBl13250P1pXEX5AoX9MtQY+KjcrR0JW3+9p0aYMonn1g43b56RM7eBlTa6l7AFB+R1qnrrAf9TTQS/a3y26yBeJ4HooUGepVa0TrorXyrwvPdbbNBThsKjizItw0tif0t0hKo6YZCjUzIPXgl9+DSTb9sm6MU9gMewI3nA9pnUVfddQRIXsRuLokulsWiI/8h4Pq6HG/8NxlwOLVsKeP2PYsiOm4v1HcT/RaDgRjO8+KR54q3w60WxhHykTFvL5WG1tIBNhUimlWJwBY29ORvsXABZhXVV7UtUMfBMGFnl69xgbACyNfvuzpqv5wtHzcPWpnR8jHAnbCzOQvNU+qw/g3DBpWjJPda5la4=
